"""changed invitation userid names

Revision ID: 1b3141cc15b9
Revises: 88c22d8a41a9
Create Date: 2022-09-12 16:29:17.697589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3141cc15b9'
down_revision = '88c22d8a41a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('user_id1', sa.Integer(), nullable=True))
    op.add_column('invitations', sa.Column('user_id2', sa.Integer(), nullable=True))
    op.drop_constraint('invitations_user_id_2_fkey', 'invitations', type_='foreignkey')
    op.drop_constraint('invitations_user_id_1_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'users', ['user_id2'], ['user_id'])
    op.create_foreign_key(None, 'invitations', 'users', ['user_id1'], ['user_id'])
    op.drop_column('invitations', 'user_id_1')
    op.drop_column('invitations', 'user_id_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('user_id_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invitations', sa.Column('user_id_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key('invitations_user_id_1_fkey', 'invitations', 'users', ['user_id_1'], ['user_id'])
    op.create_foreign_key('invitations_user_id_2_fkey', 'invitations', 'users', ['user_id_2'], ['user_id'])
    op.drop_column('invitations', 'user_id2')
    op.drop_column('invitations', 'user_id1')
    # ### end Alembic commands ###
