"""added name to recipes

Revision ID: 88c22d8a41a9
Revises: 7ec3c6b365ea
Create Date: 2022-09-07 18:35:53.194153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c22d8a41a9'
down_revision = '7ec3c6b365ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'name')
    # ### end Alembic commands ###
