"""recipes

Revision ID: e9b181438e67
Revises: f1799068aaa0
Create Date: 2023-04-14 19:55:55.406632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9b181438e67"
down_revision = "f1799068aaa0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_lists",
        sa.Column("recipe_list_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("shop_list_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.recipe_id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_list_id"],
            ["shop_lists.shop_list_id"],
        ),
        sa.PrimaryKeyConstraint("recipe_list_id"),
    )
    op.create_index(
        op.f("ix_recipe_lists_recipe_list_id"),
        "recipe_lists",
        ["recipe_list_id"],
        unique=False,
    )
    op.add_column("recipes", sa.Column("description", sa.String(), nullable=True))
    op.add_column("recipes", sa.Column("people_served", sa.Integer(), nullable=True))
    op.add_column("recipes", sa.Column("prep_time", sa.String(length=100), nullable=True))
    op.add_column(
        "recipes", sa.Column("cooking_time", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "recipes", sa.Column("resting_time", sa.String(length=100), nullable=True)
    )
    op.add_column("recipes", sa.Column("is_public", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "is_public")
    op.drop_column("recipes", "resting_time")
    op.drop_column("recipes", "cooking_time")
    op.drop_column("recipes", "prep_time")
    op.drop_column("recipes", "people_served")
    op.drop_column("recipes", "description")
    op.drop_index(op.f("ix_recipe_lists_recipe_list_id"), table_name="recipe_lists")
    op.drop_table("recipe_lists")
    # ### end Alembic commands ###
