"""first migration after disaster

Revision ID: f1799068aaa0
Revises: 
Create Date: 2022-09-13 16:07:01.894245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1799068aaa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_lists',
    sa.Column('shop_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('shop_list_id')
    )
    op.create_index(op.f('ix_shop_lists_shop_list_id'), 'shop_lists', ['shop_list_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('friendships',
    sa.Column('friendship_id', sa.Integer(), nullable=False),
    sa.Column('user_id1', sa.Integer(), nullable=True),
    sa.Column('user_id2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id1'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('friendship_id')
    )
    op.create_index(op.f('ix_friendships_friendship_id'), 'friendships', ['friendship_id'], unique=False)
    op.create_table('invitations',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('user_id1', sa.Integer(), nullable=True),
    sa.Column('user_id2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id1'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    op.create_index(op.f('ix_invitations_invitation_id'), 'invitations', ['invitation_id'], unique=False)
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('shop_list_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('was_bought', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shop_list_id'], ['shop_lists.shop_list_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_index(op.f('ix_recipes_recipe_id'), 'recipes', ['recipe_id'], unique=False)
    op.create_table('user_lists',
    sa.Column('user_list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shop_list_id', sa.Integer(), nullable=True),
    sa.Column('is_adm', sa.Boolean(), nullable=True),
    sa.Column('is_nutritionist', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shop_list_id'], ['shop_lists.shop_list_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_list_id')
    )
    op.create_index(op.f('ix_user_lists_user_list_id'), 'user_lists', ['user_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lists_user_list_id'), table_name='user_lists')
    op.drop_table('user_lists')
    op.drop_index(op.f('ix_recipes_recipe_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_invitations_invitation_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_friendships_friendship_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shop_lists_shop_list_id'), table_name='shop_lists')
    op.drop_table('shop_lists')
    # ### end Alembic commands ###
